// Code generated by MockGen. DO NOT EDIT.
// Source: s3writer/types.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	s3writer "github.com/RedHatInsights/parquet-factory/s3writer"
	gomock "github.com/golang/mock/gomock"
)

// MockS3ParquetWriter is a mock of S3ParquetWriter interface.
type MockS3ParquetWriter struct {
	ctrl     *gomock.Controller
	recorder *MockS3ParquetWriterMockRecorder
}

// MockS3ParquetWriterMockRecorder is the mock recorder for MockS3ParquetWriter.
type MockS3ParquetWriterMockRecorder struct {
	mock *MockS3ParquetWriter
}

// NewMockS3ParquetWriter creates a new mock instance.
func NewMockS3ParquetWriter(ctrl *gomock.Controller) *MockS3ParquetWriter {
	mock := &MockS3ParquetWriter{ctrl: ctrl}
	mock.recorder = &MockS3ParquetWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3ParquetWriter) EXPECT() *MockS3ParquetWriterMockRecorder {
	return m.recorder
}

// DeleteFiles mocks base method.
func (m *MockS3ParquetWriter) DeleteFiles(arg0 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFiles", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFiles indicates an expected call of DeleteFiles.
func (mr *MockS3ParquetWriterMockRecorder) DeleteFiles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFiles", reflect.TypeOf((*MockS3ParquetWriter)(nil).DeleteFiles), arg0)
}

// GetLastIndexForParquet mocks base method.
func (m *MockS3ParquetWriter) GetLastIndexForParquet(arg0 context.Context, arg1 string) map[string]int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastIndexForParquet", arg0, arg1)
	ret0, _ := ret[0].(map[string]int)
	return ret0
}

// GetLastIndexForParquet indicates an expected call of GetLastIndexForParquet.
func (mr *MockS3ParquetWriterMockRecorder) GetLastIndexForParquet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastIndexForParquet", reflect.TypeOf((*MockS3ParquetWriter)(nil).GetLastIndexForParquet), arg0, arg1)
}

// NewFile mocks base method.
func (m *MockS3ParquetWriter) NewFile(arg0 context.Context, arg1 string, arg2 interface{}) (s3writer.S3ParquetFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(s3writer.S3ParquetFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFile indicates an expected call of NewFile.
func (mr *MockS3ParquetWriterMockRecorder) NewFile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFile", reflect.TypeOf((*MockS3ParquetWriter)(nil).NewFile), arg0, arg1, arg2)
}

// Prefix mocks base method.
func (m *MockS3ParquetWriter) Prefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// Prefix indicates an expected call of Prefix.
func (mr *MockS3ParquetWriterMockRecorder) Prefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prefix", reflect.TypeOf((*MockS3ParquetWriter)(nil).Prefix))
}

// MockS3ParquetFile is a mock of S3ParquetFile interface.
type MockS3ParquetFile struct {
	ctrl     *gomock.Controller
	recorder *MockS3ParquetFileMockRecorder
}

// MockS3ParquetFileMockRecorder is the mock recorder for MockS3ParquetFile.
type MockS3ParquetFileMockRecorder struct {
	mock *MockS3ParquetFile
}

// NewMockS3ParquetFile creates a new mock instance.
func NewMockS3ParquetFile(ctrl *gomock.Controller) *MockS3ParquetFile {
	mock := &MockS3ParquetFile{ctrl: ctrl}
	mock.recorder = &MockS3ParquetFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3ParquetFile) EXPECT() *MockS3ParquetFileMockRecorder {
	return m.recorder
}

// AddRow mocks base method.
func (m *MockS3ParquetFile) AddRow(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRow", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRow indicates an expected call of AddRow.
func (mr *MockS3ParquetFileMockRecorder) AddRow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRow", reflect.TypeOf((*MockS3ParquetFile)(nil).AddRow), arg0)
}

// CloseFile mocks base method.
func (m *MockS3ParquetFile) CloseFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseFile indicates an expected call of CloseFile.
func (mr *MockS3ParquetFileMockRecorder) CloseFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseFile", reflect.TypeOf((*MockS3ParquetFile)(nil).CloseFile))
}
